export enum RouteName {
  Login = "login",
  LogoutConfirm = "logout-confirm",
  Dashboard = "dashboard",
  Insertions = "insertions",
  Farms = "data/farms",
  Houses = "data/houses",
  Hatcheries = "data/hatcheries",
  Settings = "settings",
  Users = "users",
  UserProfile = "user-profile",
  NotFound = "not-found",
  Forbidden = "forbidden",
  InternalServerError = "internal-server-error",
}
