services:
  farms_manager_backend:
    image: ghcr.io/filipbart/farms-manager:latest
    container_name: fm-container
    restart: always
    ports:      
      - "8082:8082"
    volumes:
      - ./config.toml:/app/config.toml
    